/*===========================================================================*
* Flow:         natdis_project_flow.flw
* ID:           
* Created:      2026-08-07T02:55:16.61Z
* Created by:   student
* Modified:     2026-08-07T02:55:16.61Z
* Modified by:  student
*
* Version:       DataFlows lts 2025.09 (20260106.1767663513650)
*
* Generated On:  2026-08-07T15:31:54.248264521Z
* Generated by:  student
*============================================================================*/

/* region: Generated flow setup */
%let flow_id = ;
%let flow_name = natdis_project_flow.flw;
%let flow_place = ;
%let flow_location = ;
%macro _flw_action_start(nodes);
    data _null_;
        dtEndStr = put(datetime(), E8601DZ.);
        put "_FLW_ACTION_START_|" dtEndStr +(-1) "|&nodes";
    run;
%mend _flw_action_start;
%macro _flw_action_end(nodes, table_libs, libs, table_names);
    data _null_;

        attrib next_table_name length = $32 informat = $32. format = $32.
               dtStartStr length = $26 informat = $26. format = $26.;

        %local i next_table;
        %do i=1 %to %sysfunc(countc(&table_libs, |)) + 1;
            %let next_table = %qscan(&table_libs, &i, |);
            %let next_lib = %qscan(&libs, &i, |);
            %let next_table_name = %qscan(&table_names, &i, |);
            next_table_name = kreverse(ksubstr(kreverse(ksubstr(kstrip("&next_table_name."),2)),2));
            %let table_exists = %eval(%sysfunc(exist(&next_table, data)) or %sysfunc(exist(&next_table, view)));
            put "_FLW_ACTION_TABLE_|&next_lib|" next_table_name +(-1) "|&table_exists";
        %end;
        dtStartStr = put(datetime(), E8601DZ.);
        put "_FLW_ACTION_END_|" dtStartStr +(-1) "|&nodes";
    run;
%mend _flw_action_end;

/* endregion */

/* region: Generated step setup */
%_flw_action_start(05167750-920b-11f1-bb51-5f70b651b20c);
/* endregion */
/*===========================================================================*
* Node name:        1. Setup and Initial Data Load
* Node ID:          05167750-920b-11f1-bb51-5f70b651b20c
* Flow:             natdis_project_flow.flw
*
*
*============================================================================*/

/*===========================================================================*
* Node name:        1_1_parameters.sas
* Node ID:          967eb2d0-920a-11f1-bb51-5f70b651b20c
*
* Output Tables:
*   WORK._flw000967eb2d0920a11f1_0_0_1
*
* Step name:        SAS Program
* Step path:        /dataFlows/steps/a7190700-f59c-4a94-afe2-214ce639fcde
* Step description: Run user written SAS code.
*----------------------------------------------------------------------------*/

/* region: Generated step setup */

%_flw_action_start(967eb2d0-920a-11f1-bb51-5f70b651b20c);
/* endregion */


/* region: Generated macro initialization */
%let _inputCount = 0;
%let _outputCount = 1;
%let _output1 = WORK._flw000967eb2d0920a11f1_0_0_1;

/* endregion */

FILENAME _flw_pr "/home/student/github_bruno/student/brunosastre/natdis_project/01_setup_load/1_1_parameters.sas" encoding="UTF-8";
%include _flw_pr / source2;
filename _flw_pr clear;

/* region: Generated macro cleanup */
%symdel _inputCount / nowarn;
%symdel _outputCount / nowarn;
%symdel _output1 / nowarn;

/* endregion */


/* region: Generated step cleanup for 1_1_parameters.sas */
%_flw_action_end(967eb2d0-920a-11f1-bb51-5f70b651b20c, WORK._flw000967eb2d0920a11f1_0_0_1, WORK, "_flw000967eb2d0920a11f1_0_0_1");
/* endregion */

/*===========================================================================*
* Node name:        1_2_libname_cas_setup_load.sas
* Node ID:          981b24c0-920a-11f1-bb51-5f70b651b20c
*
* Input Tables:
*   WORK._flw000967eb2d0920a11f1_0_0_1
*
* Output Tables:
*   WORK._flw000981b24c0920a11f1_0_0_2
*
* Step name:        SAS Program
* Step path:        /dataFlows/steps/a7190700-f59c-4a94-afe2-214ce639fcde
* Step description: Run user written SAS code.
*----------------------------------------------------------------------------*/

/* region: Generated step setup */

%_flw_action_start(981b24c0-920a-11f1-bb51-5f70b651b20c);
/* endregion */


/* region: Generated macro initialization */
%let _inputCount = 1;
%let _outputCount = 1;
%let _input1 = WORK._flw000967eb2d0920a11f1_0_0_1;
%let _output1 = WORK._flw000981b24c0920a11f1_0_0_2;

/* endregion */

FILENAME _flw_pr "/home/student/github_bruno/student/brunosastre/natdis_project/01_setup_load/1_2_libname_cas_setup_load.sas" encoding="UTF-8";
%include _flw_pr / source2;
filename _flw_pr clear;

/* region: Generated macro cleanup */
%symdel _inputCount / nowarn;
%symdel _outputCount / nowarn;
%symdel _input1 / nowarn;
%symdel _output1 / nowarn;

/* endregion */


/* region: Generated step cleanup for 1_2_libname_cas_setup_load.sas */
%_flw_action_end(981b24c0-920a-11f1-bb51-5f70b651b20c, WORK._flw000981b24c0920a11f1_0_0_2, WORK, "_flw000981b24c0920a11f1_0_0_2");
/* endregion */

/*===========================================================================*
* Node name:        1_3_functions.sas
* Node ID:          9bd7b790-920a-11f1-bb51-5f70b651b20c
*
* Input Tables:
*   WORK._flw000981b24c0920a11f1_0_0_2
*
* Output Tables:
*   WORK._flw0009bd7b790920a11f1_0_0_3
*
* Step name:        SAS Program
* Step path:        /dataFlows/steps/a7190700-f59c-4a94-afe2-214ce639fcde
* Step description: Run user written SAS code.
*----------------------------------------------------------------------------*/

/* region: Generated step setup */

%_flw_action_start(9bd7b790-920a-11f1-bb51-5f70b651b20c);
/* endregion */


/* region: Generated macro initialization */
%let _inputCount = 1;
%let _outputCount = 1;
%let _input1 = WORK._flw000981b24c0920a11f1_0_0_2;
%let _output1 = WORK._flw0009bd7b790920a11f1_0_0_3;

/* endregion */

FILENAME _flw_pr "/home/student/github_bruno/student/brunosastre/natdis_project/01_setup_load/1_3_functions.sas" encoding="UTF-8";
%include _flw_pr / source2;
filename _flw_pr clear;

/* region: Generated macro cleanup */
%symdel _inputCount / nowarn;
%symdel _outputCount / nowarn;
%symdel _input1 / nowarn;
%symdel _output1 / nowarn;

/* endregion */


/* region: Generated step cleanup for 1_3_functions.sas */
%_flw_action_end(9bd7b790-920a-11f1-bb51-5f70b651b20c, WORK._flw0009bd7b790920a11f1_0_0_3, WORK, "_flw0009bd7b790920a11f1_0_0_3");
/* endregion */

/* region: Generated sub flow cleanup for 1. Setup and Initial Data Load */
%_flw_action_end(05167750-920b-11f1-bb51-5f70b651b20c,,,);
/* endregion */

/* region: Generated step setup */
%_flw_action_start(05173aa0-920b-11f1-bb51-5f70b651b20c);
/* endregion */
/*===========================================================================*
* Node name:        2. Transform and Data Quality
* Node ID:          05173aa0-920b-11f1-bb51-5f70b651b20c
* Flow:             natdis_project_flow.flw
*
*
*============================================================================*/

/*===========================================================================*
* Node name:        2_1_transform.sas
* Node ID:          c7940190-920a-11f1-bb51-5f70b651b20c
*
* Output Tables:
*   WORK._flw000c7940190920a11f1_0_0_4
*
* Step name:        SAS Program
* Step path:        /dataFlows/steps/a7190700-f59c-4a94-afe2-214ce639fcde
* Step description: Run user written SAS code.
*----------------------------------------------------------------------------*/

/* region: Generated step setup */

%_flw_action_start(c7940190-920a-11f1-bb51-5f70b651b20c);
/* endregion */


/* region: Generated macro initialization */
%let _inputCount = 0;
%let _outputCount = 1;
%let _output1 = WORK._flw000c7940190920a11f1_0_0_4;

/* endregion */

FILENAME _flw_pr "/home/student/github_bruno/student/brunosastre/natdis_project/02_transform_dataquality/2_1_transform.sas" encoding="UTF-8";
%include _flw_pr / source2;
filename _flw_pr clear;

/* region: Generated macro cleanup */
%symdel _inputCount / nowarn;
%symdel _outputCount / nowarn;
%symdel _output1 / nowarn;

/* endregion */


/* region: Generated step cleanup for 2_1_transform.sas */
%_flw_action_end(c7940190-920a-11f1-bb51-5f70b651b20c, WORK._flw000c7940190920a11f1_0_0_4, WORK, "_flw000c7940190920a11f1_0_0_4");
/* endregion */

/*===========================================================================*
* Node name:        2_2_dq.sas
* Node ID:          c93f67a0-920a-11f1-bb51-5f70b651b20c
*
* Input Tables:
*   WORK._flw000c7940190920a11f1_0_0_4
*
* Output Tables:
*   WORK._flw000c93f67a0920a11f1_0_0_5
*
* Step name:        SAS Program
* Step path:        /dataFlows/steps/a7190700-f59c-4a94-afe2-214ce639fcde
* Step description: Run user written SAS code.
*----------------------------------------------------------------------------*/

/* region: Generated step setup */

%_flw_action_start(c93f67a0-920a-11f1-bb51-5f70b651b20c);
/* endregion */


/* region: Generated macro initialization */
%let _inputCount = 1;
%let _outputCount = 1;
%let _input1 = WORK._flw000c7940190920a11f1_0_0_4;
%let _output1 = WORK._flw000c93f67a0920a11f1_0_0_5;

/* endregion */

FILENAME _flw_pr "/home/student/github_bruno/student/brunosastre/natdis_project/02_transform_dataquality/2_2_dq.sas" encoding="UTF-8";
%include _flw_pr / source2;
filename _flw_pr clear;

/* region: Generated macro cleanup */
%symdel _inputCount / nowarn;
%symdel _outputCount / nowarn;
%symdel _input1 / nowarn;
%symdel _output1 / nowarn;

/* endregion */


/* region: Generated step cleanup for 2_2_dq.sas */
%_flw_action_end(c93f67a0-920a-11f1-bb51-5f70b651b20c, WORK._flw000c93f67a0920a11f1_0_0_5, WORK, "_flw000c93f67a0920a11f1_0_0_5");
/* endregion */

/* region: Generated sub flow cleanup for 2. Transform and Data Quality */
%_flw_action_end(05173aa0-920b-11f1-bb51-5f70b651b20c,,,);
/* endregion */

/* region: Generated step setup */
%_flw_action_start(235d5210-920b-11f1-bb51-5f70b651b20c);
/* endregion */
/*===========================================================================*
* Node name:        3. Join, Generate Reporting Tables and Cleanup
* Node ID:          235d5210-920b-11f1-bb51-5f70b651b20c
* Flow:             natdis_project_flow.flw
*
*
*============================================================================*/

/*===========================================================================*
* Node name:        3_1_join_and_generate_reporting_tables.sas
* Node ID:          235c8ec0-920b-11f1-bb51-5f70b651b20c
*
* Output Tables:
*   WORK._flw000235c8ec0920b11f1_0_0_6
*
* Step name:        SAS Program
* Step path:        /dataFlows/steps/a7190700-f59c-4a94-afe2-214ce639fcde
* Step description: Run user written SAS code.
*----------------------------------------------------------------------------*/

/* region: Generated step setup */

%_flw_action_start(235c8ec0-920b-11f1-bb51-5f70b651b20c);
/* endregion */


/* region: Generated macro initialization */
%let _inputCount = 0;
%let _outputCount = 1;
%let _output1 = WORK._flw000235c8ec0920b11f1_0_0_6;

/* endregion */

FILENAME _flw_pr "/home/student/github_bruno/student/brunosastre/natdis_project/03_join_and_report/3_1_join_and_generate_reporting_tables.sas" encoding="UTF-8";
%include _flw_pr / source2;
filename _flw_pr clear;

/* region: Generated macro cleanup */
%symdel _inputCount / nowarn;
%symdel _outputCount / nowarn;
%symdel _output1 / nowarn;

/* endregion */


/* region: Generated step cleanup for 3_1_join_and_generate_reporting_tables.sas */
%_flw_action_end(235c8ec0-920b-11f1-bb51-5f70b651b20c, WORK._flw000235c8ec0920b11f1_0_0_6, WORK, "_flw000235c8ec0920b11f1_0_0_6");
/* endregion */

/*===========================================================================*
* Node name:        4_1_cleanup.sas
* Node ID:          2697e3a0-920b-11f1-bb51-5f70b651b20c
*
* Input Tables:
*   WORK._flw000235c8ec0920b11f1_0_0_6
*
* Output Tables:
*   WORK._flw0002697e3a0920b11f1_0_0_7
*
* Step name:        SAS Program
* Step path:        /dataFlows/steps/a7190700-f59c-4a94-afe2-214ce639fcde
* Step description: Run user written SAS code.
*----------------------------------------------------------------------------*/

/* region: Generated step setup */

%_flw_action_start(2697e3a0-920b-11f1-bb51-5f70b651b20c);
/* endregion */


/* region: Generated macro initialization */
%let _inputCount = 1;
%let _outputCount = 1;
%let _input1 = WORK._flw000235c8ec0920b11f1_0_0_6;
%let _output1 = WORK._flw0002697e3a0920b11f1_0_0_7;

/* endregion */

FILENAME _flw_pr "/home/student/github_bruno/student/brunosastre/natdis_project/04_cleanup/4_1_cleanup.sas" encoding="UTF-8";
%include _flw_pr / source2;
filename _flw_pr clear;

/* region: Generated macro cleanup */
%symdel _inputCount / nowarn;
%symdel _outputCount / nowarn;
%symdel _input1 / nowarn;
%symdel _output1 / nowarn;

/* endregion */


/* region: Generated step cleanup for 4_1_cleanup.sas */
%_flw_action_end(2697e3a0-920b-11f1-bb51-5f70b651b20c, WORK._flw0002697e3a0920b11f1_0_0_7, WORK, "_flw0002697e3a0920b11f1_0_0_7");
/* endregion */

/* region: Generated sub flow cleanup for 3. Join, Generate Reporting Tables and Cleanup */
%_flw_action_end(235d5210-920b-11f1-bb51-5f70b651b20c,,,);
/* endregion */

/* region: Generated step setup */
%_flw_action_start(269831c0-920b-11f1-bb51-5f70b651b20c);
/* endregion */
/*===========================================================================*
* Node name:        4. Report generation and Increment Data
* Node ID:          269831c0-920b-11f1-bb51-5f70b651b20c
* Flow:             natdis_project_flow.flw
*
*
*============================================================================*/

/*===========================================================================*
* Node name:        5_reports.sas
* Node ID:          2ec4c8e0-920b-11f1-bb51-5f70b651b20c
*
* Output Tables:
*   WORK._flw0002ec4c8e0920b11f1_0_0_8
*
* Step name:        SAS Program
* Step path:        /dataFlows/steps/a7190700-f59c-4a94-afe2-214ce639fcde
* Step description: Run user written SAS code.
*----------------------------------------------------------------------------*/

/* region: Generated step setup */

%_flw_action_start(2ec4c8e0-920b-11f1-bb51-5f70b651b20c);
/* endregion */


/* region: Generated macro initialization */
%let _inputCount = 0;
%let _outputCount = 1;
%let _output1 = WORK._flw0002ec4c8e0920b11f1_0_0_8;

/* endregion */

FILENAME _flw_pr "/home/student/github_bruno/student/brunosastre/natdis_project/05_reports/5_reports.sas" encoding="UTF-8";
%include _flw_pr / source2;
filename _flw_pr clear;

/* region: Generated macro cleanup */
%symdel _inputCount / nowarn;
%symdel _outputCount / nowarn;
%symdel _output1 / nowarn;

/* endregion */


/* region: Generated step cleanup for 5_reports.sas */
%_flw_action_end(2ec4c8e0-920b-11f1-bb51-5f70b651b20c, WORK._flw0002ec4c8e0920b11f1_0_0_8, WORK, "_flw0002ec4c8e0920b11f1_0_0_8");
/* endregion */

/*===========================================================================*
* Node name:        6_increment_data.sas
* Node ID:          35c0a830-920b-11f1-bb51-5f70b651b20c
*
* Input Tables:
*   WORK._flw0002ec4c8e0920b11f1_0_0_8
*
* Output Tables:
*   WORK._flw00035c0a830920b11f1_0_0_9
*
* Step name:        SAS Program
* Step path:        /dataFlows/steps/a7190700-f59c-4a94-afe2-214ce639fcde
* Step description: Run user written SAS code.
*----------------------------------------------------------------------------*/

/* region: Generated step setup */

%_flw_action_start(35c0a830-920b-11f1-bb51-5f70b651b20c);
/* endregion */


/* region: Generated macro initialization */
%let _inputCount = 1;
%let _outputCount = 1;
%let _input1 = WORK._flw0002ec4c8e0920b11f1_0_0_8;
%let _output1 = WORK._flw00035c0a830920b11f1_0_0_9;

/* endregion */

FILENAME _flw_pr "/home/student/github_bruno/student/brunosastre/natdis_project/06_increment_2023_2024/6_increment_data.sas" encoding="UTF-8";
%include _flw_pr / source2;
filename _flw_pr clear;

/* region: Generated macro cleanup */
%symdel _inputCount / nowarn;
%symdel _outputCount / nowarn;
%symdel _input1 / nowarn;
%symdel _output1 / nowarn;

/* endregion */


/* region: Generated step cleanup for 6_increment_data.sas */
%_flw_action_end(35c0a830-920b-11f1-bb51-5f70b651b20c, WORK._flw00035c0a830920b11f1_0_0_9, WORK, "_flw00035c0a830920b11f1_0_0_9");
/* endregion */

/* region: Generated sub flow cleanup for 4. Report generation and Increment Data */
%_flw_action_end(269831c0-920b-11f1-bb51-5f70b651b20c,,,);
/* endregion */

/* region: Generated flow cleanup */
%sysmacdelete _flw_action_start;
%sysmacdelete _flw_action_end;

/* endregion */

